config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lost_reports, path: 'extravios' do
    resource :flyer do
      get :show
      get :preview
    end
  end

  resources :adoptions, path: 'adopciones'
  resources :users, only: [:show, :edit, :update]
  resources :invites, only: :create

  get 'contacto', to: 'main#contact', as: 'contact'
  get 'perfil', to: 'users#show', as: 'profile'

  root 'adoptions#index'
end

app/models/lost_report.rb
class LostReport < ActiveRecord::Base
  paginates_per 12

  belongs_to :province
  belongs_to :pet
  belongs_to :user
  accepts_nested_attributes_for :pet, allow_destroy: true
  delegate :name, :avatar, :breed_name, to: :pet, prefix: true
  delegate :animal_type_name, to: :pet

  serialize :phone_numbers
  before_validation :strip_phone_numbers
  validates :phone_numbers, phone_number: true
  validates_presence_of :address, :description

  default_scope { order('created_at DESC') }

  def phone_numbers
    (super || []).reject(&:blank?)
  end

  private

  def strip_phone_numbers
    self.phone_numbers = phone_numbers.map { |phone_number| phone_number.delete('^0-9') }
  end
end

# == Schema Information
#
# Table name: lost_reports
#
#  id            :integer          not null, primary key
#  address       :text
#  reward        :integer
#  owner         :string
#  description   :text
#  created_at    :datetime
#  updated_at    :datetime
#  province_id   :integer
#  pet_id        :integer
#  phone_numbers :text
#  user_id       :integer
#  found         :boolean          default(FALSE)
#

app/controllers/lost_reports_controller.rb
class LostReportsController < ApplicationController
  before_filter :find_lost_report, only: [:show, :edit, :update]
  before_filter :validate_owner, only: [:edit, :update]
  before_filter :find_all_lost_reports, only: [:index]
  before_filter :filter_lost_reports, only: [:index]
  before_action :authenticate_user!, only: [:new, :edit]

  def index; end

  def new
    @lost_report = LostReport.new
    @lost_report.build_pet
  end

  def create
    @lost_report = current_user.lost_reports.new(lost_report_params)
    @lost_report.owner = current_user.name
    if @lost_report.save
      redirect_to lost_report_path(@lost_report)
    else
      flash.now[:error] = @lost_report.errors.messages
      render 'new'
    end
  end

  def edit; end

  def show; end

  def update
    if @lost_report.update(lost_report_params)
      redirect_to lost_report_path(@lost_report)
    else
      flash.now[:error] = @lost_report.errors.messages
      render 'edit'
    end
  end

  private

  def find_all_lost_reports
    @pet_reports = LostReport.all.page params[:page]
  end

  def filter_lost_reports
    if params[:province].nil? || params[:province][:province_id].empty?
      find_all_lost_reports
    else
      @pet_reports = find_all_lost_reports.where(province_id: params[:province][:province_id]).page params[:page]
      @province_id = params[:province][:province_id]
    end
  end

  def find_lost_report
    @lost_report = LostReport.find(params[:id])
  end

  def validate_owner
    redirect_to root_path unless current_user == @lost_report.user
  end

  def lost_report_params
    params.require(:lost_report).permit(
      :province_id,
      :address,
      :description,
      :reward,
      :found,
      phone_numbers: [],
      pet_attributes: [:id, :name, :breed_id, :sex, :avatar]
    )
  end
end

app/views/lost_reports/_form.html.erb
<%= form_for(@lost_report, html: { class: 'job-manager-form'}) do |f, pet = @lost_report.pet| %>
  <%= render 'shared/flash_messages' %>

  <%= f.fields_for :pet do |pet_form| %>
    <% if !pet.new_record? %>
      <fieldset>
        <div class='large-6 columns'>
          <div class="checkbox checkbox__custom checkbox__style4">
            <label>
              <%= f.check_box :found %>
              <span>¿Ya apareció la mascota?</span>
            </label>
          </div>
        </div>
      </fieldset>
    <% end %>

    <fieldset>
      <label>Foto de perfil <span class="required">*</span></label>
      <div class="field">
        <div class='profile-pic-box'>
          <% profile_img = !pet.new_record? ? pet.avatar.url(:profile) : 'profile-default.png' %>
          <%= image_tag profile_img, id: 'image', class: 'img-rounded' %>
        </div>
      </div>

      <div class="field">
        <div class='fileUpload btn btn-primary btn-sm'>
          <span>Subir imagen</span>
          <%= pet_form.file_field :avatar, { id: 'image-selector', class: 'upload' } %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <label>Nombre de la mascota <span class="required">*</span></label>
      <div class="field">
        <% @focus = pet.new_record? %>
        <%= pet_form.text_field :name, placeholder: 'ej. Misingo', class: 'form-control', autofocus: @focus  %>
      </div>
    </fieldset>

    <fieldset>
      <div class="row">
        <div class="col-md-6">
          <div class="radio radio__custom radio__style4">
            <label>
              <%= pet_form.radio_button :sex, 'Macho', checked: true %>
              <span>Es macho</span>
            </label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="radio radio__custom radio__style4">
            <label>
              <%= pet_form.radio_button :sex, 'Hembra'%>
              <span>Es hembra</span>
            </label>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="row">
      <div class="col-md-6">
        <fieldset class="fieldset-job_type">
          <label>Animal</label>
          <div class="field select-style">
            <% animal_selected = pet.new_record? ? 0 : pet.breed.animal_type_id %>
            <%= select_tag :animal_type_id, options_from_collection_for_select(AnimalType.all, :id, :name, selected: animal_selected), class: 'form-control' %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset>
          <label>Raza</label>
          <div class="field select-style">
            <% breed_selected = pet.new_record? ? 1 : pet.breed.id %>
            <%= pet_form.select :breed_id, options_for_select(Breed.order(:name).map{ |c| [c.name, c.id, { data: { animal_type: c.animal_type_id } } ] }, selected: breed_selected), {}, {class: 'form-control', id: 'pet_breed_id'} %>
          </div>
        </fieldset>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <fieldset class="fieldset-job_type">
        <label> ¿En qué provincia se perdió tu mascota?</label>
        <div class="field select-style">
          <% province_selected = @lost_report.new_record? ? 0 : @lost_report.province_id %>
          <%= collection_select(:lost_report, :province_id, Province.all, :id, :name, {selected: province_selected}, {class: 'form-control'}) %>
        </div>
      </fieldset>
    </div>
  </div>

  <fieldset>
    <div class="field">
      <label> ¿Cuál es la dirección exacta del extravío?  <span class="required">*</span></label>
      <%= f.text_area :address, placeholder: 'Mencioná también lugares aledaños', class: 'form-control' %>
    </div>
  </fieldset>

  <div class='row'>
    <div class="col-md-6">
      <fieldset>
        <label>Número de teléfono <span class="required">*</span></label>
        <%= f.text_field :phone_numbers, value: @lost_report.phone_numbers[0], name: 'lost_report[phone_numbers][]', class: 'form-control', placeholder: 'ej. 88112233' %>
      </fieldset>
    </div>
    <div class="col-md-6">
      <fieldset>
        <label>Otro teléfono (opcional)</label>
        <%= f.text_field :phone_numbers, value: @lost_report.phone_numbers[1] , name: 'lost_report[phone_numbers][]', class: 'form-control', placeholder: 'ej. 88112244' %>
      </fieldset>
    </div>
  </div>

  <fieldset>
    <div class="field">
        <label>Mencioná características de tu mascota <span class="required">*</span></label>
        <%= f.text_area :description, placeholder: '¿Llevaba collar?, ¿Padece de alguna enfermedad?', class: 'form-control' %>
      </div>
    </fieldset>
  </fieldset>

  <fieldset>
    <div class='large-6 columns'>
      <div class="checkbox checkbox__custom checkbox__style4">
        <label>
          <%= f.check_box :reward %>
          <span>Ofrezco recompensa</span>
        </label>
      </div>
    </div>
  </fieldset>

  <p>
    <% text = @lost_report.pet.new_record? ? 'Agregar a mi mascota' : 'Guardar cambios' %>
    <%= f.submit text, class: 'btn btn-primary', data: { disable_with: 'Guardando' } %>
  </p>
<% end %>

<script type='text/javascript'>
  <% if !@lost_report.pet.new_record? %>
    setTimeout(function(){
      $('#pet_breed_id').val('<%= @lost_report.pet.breed.id %>');
    },100);
  <% end %>
</script>

app/views/lost_reports/_found_info.html.erb
<% pet = lost_report.pet %>

<div class="pet-name">
  <p>¡Ya encontramos a <%= pet.name %>! <%= link_to '(editar mascota)', edit_lost_report_path(lost_report) if current_user == lost_report.user %></p>
</div>

<fieldset class="pet-field">
  <%= image_tag("breed_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= pet.breed_name %></b> (<%= pet.sex %>)
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("location_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= lost_report.province.name %></b>. <%= lost_report.address %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <%= lost_report.description %>
  </div>
</fieldset>

app/views/lost_reports/_social_share_buttons.html.erb
<% pet = lost_report.pet %>
<div class="alert alert-warning alert-dismissable social-share">
  <strong>¡No olvidés compartirlo en redes sociales!</strong>
  <% url = lost_report_url(lost_report) %>
  <div id='fb-root'></div>
  <div class="social-networks-buttons">
    <div class='fb-like' data-href='<%= url %>' data-layout='button' data-action='like' data-show-faces='true' data-share='true'></div>
    <a href='https://twitter.com/share' class='twitter-share-button' data-url='<%= url %>' data-text="¡Ayudame a encontrar a <%= @lost_report.pet.name %>! RT #Misingo" data-via='misingocom' data-count='none'>Tweet</a>
  </div>
</div>

app/views/lost_reports/_social_share_meta_tags.html.erb
<% content_for :facebook_meta_tags do %>
  <%= render 'shared/facebook_meta_tags' %>
  <meta property="og:url" content="<%= request.base_url + lost_report_path(@lost_report) %>" />
  <meta property="og:title" content="¡Se busca <%= @lost_report.pet.name %>!" />
  <meta property="og:description" content="<%= @lost_report.description %>. Llamar al <%= @lost_report.phone_numbers.join(' / ') %>" />
  <meta property="og:image" content="<%= @lost_report.pet.avatar.url(:preview) %>" />
<% end %>
<% content_for :twitter_meta_tags do %>
  <%= render 'shared/twitter_meta_tags' %>
  <meta name="twitter:title" content="¡Se busca <%= @lost_report.pet.name %>! | Misingo">
  <meta name="twitter:description" content="<%= @lost_report.description %>. Llamar al <%= @lost_report.phone_numbers.join(' / ') %>">
  <meta name="twitter:image" content="<%= @lost_report.pet.avatar.url(:preview) %>">
<% end %>

app/views/lost_reports/_social_share_options.html.erb
<% pet = lost_report.pet %>
<div class="alert alert-warning alert-dismissable social-share">
  <strong>¡No olvidés compartirlo en redes sociales!</strong>
  <% url = lost_report_url(lost_report) %>
  <div id='fb-root'></div>
  <div class="social-networks-buttons">
    <div class='fb-like' data-href='<%= url %>' data-layout='button' data-action='like' data-show-faces='true' data-share='true'></div>
    <a href='https://twitter.com/share' class='twitter-share-button' data-url='<%= url %>' data-text="¡Ayudame a encontrar a <%= @lost_report.pet.name %>!" data-via='misingocom' data-count='none'>Tweet</a>
  </div>
</div>

app/views/lost_reports/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: "Editar datos de #{@lost_report.pet.name}" } %>

<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/lost_reports/flyer.html.erb
<div>
  <%= image_tag @flyer_image %></a>
</div>

app/views/lost_reports/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: 'Mascotas desaparecidas' } %>

<div class="row search">
  <div class="col-md-6 col-md-offset-4">
    <fieldset>
      <%= form_tag(lost_reports_path, method: 'get') do %>
        <div class="col-md-6">
          <%= collection_select(:province, :province_id, Province.all, :id, :name,
          { include_blank: 'Provincias', selected: @province_id }, { class: 'form-control' }) %>
        </div>
        <div class="col-md-6">
          <%= button_tag('Buscar', class: 'btn btn-sm btn-default search') %>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>

<%= render 'shared/pets_grid' %>

app/views/lost_reports/new.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: 'Agregar mascota extraviada' } %>

<section class="page-content">
  <div class="container">  
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/lost_reports/show.html.erb
<%= render 'social_share_meta_tags' %>
<%= render 'shared/header' %>
<% text = @lost_report.found ? 'Ya encontramos a' : 'Se busca' %>
<%= render 'shared/page_heading', { heading: "#{text} #{@lost_report.pet.name}" } %>

<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="pet-image col-md-7">
        <%= image_tag(@lost_report.pet.avatar.url(:large), class: 'img-thumbnail') %>
        <%= render 'social_share_buttons', { lost_report: @lost_report } %>
      </div>
      <div class="col-md-5">
        <% if @lost_report.found %>
          <%= render 'found_info', { lost_report: @lost_report } %>
          <div class="alert alert-warning alert-dismissable flyer-container">
            <strong><%= "¡Ya encontramos a #{@lost_report.pet.name}! Gracias por tu ayuda." %></strong>
            <%= render 'shared/site_slogan' %>
          </div>
        <% else %>
          <%= render 'shared/lost_report_info', { lost_report: @lost_report } %>
          <%= render 'shared/flyer_preview', { lost_report: @lost_report } %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/lost_reports/update.js.erb
console.log('Lost report updated!!');