config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lost_reports, path: 'extravios' do
    resource :flyer do
      get :show
      get :preview
    end
  end

  resources :adoptions, path: 'adopciones'
  resources :users, only: [:show, :edit, :update]
  resources :invites, only: :create

  get 'contacto', to: 'main#contact', as: 'contact'
  get 'perfil', to: 'users#show', as: 'profile'

  root 'adoptions#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_many :lost_reports, dependent: :destroy
  has_many :adoptions, dependent: :destroy
  validates_format_of :name, with: /^[\D]*$/, multiline: true

  def self.from_omniauth(auth)
    # uid: Standard name for provider's user ID
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  provider               :string
#  uid                    :string
#  name                   :string
#  image                  :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  prepend_before_action :find_user, only: [:show]

  def show
    @pet_reports = @user.adoptions + @user.lost_reports
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      flash.now[:error] = current_user.errors.messages
      render 'edit'
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email
    )
  end
end

app/views/users/_form.html.erb
<%= form_for(current_user, html: { class: 'job-manager-form' }) do |f| %>
  <%= render 'shared/flash_messages' %>

  <fieldset>
    <label>Nombre <span class="required">*</span></label>
    <div class="field">
      <%= f.text_field :name, id: 'name', class: "form-control", autofocus: true, required: true  %>
    </div>
  </fieldset>

  <fieldset>
    <label>Correo electrónico <span class="required">*</span></label>
    <div class="field">
      <%= f.text_field :email, id: 'email', class: "form-control", autofocus: true, required: true  %>
    </div>
  </fieldset>

  <p>
    <%= f.submit 'Guardar', class: 'btn btn-primary', data: { disable_with: 'Guardando' } %>
  </p>
<% end %>

app/views/users/_user_info.html.erb
<center>
  <div class='panel radius profile'>
    <%= current_user.image.nil? ? image_tag('profile_default.png', class: 'profile') : image_tag(current_user.image) %>
    <div class='row final'></div>
    <label><b><%= current_user.name %></b></label>
    <% if current_user.provider.nil? %>
      <label><b><%= current_user.email %></b></label>
    <% end %>
  </div>
  <%= link_to 'Registrar mascota desaparecida', new_lost_report_path, class: 'small button' %>
</center>

app/views/users/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: "Editar datos de #{current_user.name}" } %>

<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div class="site-wrapper">

  <%= render 'shared/header'%>

    <!-- Main -->
    <div class="main" role="main">

      <!-- Slider -->
      <!-- Slider / End -->

      <!-- Page Content -->
      <section class="page-content">
        <div class="container">

          <!-- Light Section -->
          <section class="section-light section-nomargin">
            <div class="row">
              <div class="col-md-8">
                <h2 class="with-subtitle" data-animation="fadeInUp" data-animation-delay="0">Latest Listings <small data-animation="fadeInUp" data-animation-delay="100">Subtitle goes here</small></h2>
                <div class="row">
                  <div class="col-xs-6 col-sm-3 col-md-3" data-animation="fadeInLeft" data-animation-delay="0">
                    <div class="job-listing-box">
                      <figure class="job-listing-img">
                        <a href="job-profile.html"><img src="http://placehold.it/160x160" alt=""></a>
                      </figure>
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">Samantha Doe</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Cat Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 1 day ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                  <div class="col-xs-6 col-sm-3 col-md-3" data-animation="fadeInLeft" data-animation-delay="200">
                    <div class="job-listing-box">
                      <figure class="job-listing-img">
                        <a href="job-profile.html"><img src="http://placehold.it/160x160" alt=""></a>
                      </figure>
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">Molly Warren</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Dog Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 2 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>

                  <div class="clearfix visible-xs"></div>
                  <div class="spacer visible-xs"></div>

                  <div class="col-xs-6 col-sm-3 col-md-3" data-animation="fadeInLeft" data-animation-delay="400">
                    <div class="job-listing-box">
                      <figure class="job-listing-img">
                        <a href="job-profile.html"><img src="http://placehold.it/160x160" alt=""></a>
                      </figure>
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">Jeff Black</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Pet Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 3 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                  <div class="col-xs-6 col-sm-3 col-md-3" data-animation="fadeInLeft" data-animation-delay="600">
                    <div class="job-listing-box">
                      <figure class="job-listing-img">
                        <a href="job-profile.html"><img src="http://placehold.it/160x160" alt=""></a>
                      </figure>
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">Susan Smith</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Cat Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 5 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4" data-animation="fadeInRight" data-animation-delay="0">
                <div class="spacer-lg visible-sm visible-xs"></div>
                <h2>Featured Listings</h2>
                <!-- Featured Listings -->
                <div class="owl-carousel owl-theme owl-featured-listings">
                  <div class="job-listing-box featured">
                    <figure class="job-listing-img">
                      <a href="job-profile.html"><img src="http://placehold.it/708x671" alt=""></a>
                    </figure>
                    <div class="job-listing-holder">
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">John Doe</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Cat Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 5 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                  <div class="job-listing-box featured">
                    <figure class="job-listing-img">
                      <a href="job-profile.html"><img src="http://placehold.it/708x671" alt=""></a>
                    </figure>
                    <div class="job-listing-holder">
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">John Doe</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Cat Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 5 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                  <div class="job-listing-box featured">
                    <figure class="job-listing-img">
                      <a href="job-profile.html"><img src="http://placehold.it/708x671" alt=""></a>
                    </figure>
                    <div class="job-listing-holder">
                      <div class="job-listing-body">
                        <h4 class="name"><a href="job-profile.html">John Doe</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                      <footer class="job-listing-footer">
                        <ul class="meta">
                          <li class="category">Cat Sitter</li>
                          <li class="location"><a href="#">Orlando, FL</a></li>
                          <li class="date">Posted 5 days ago</li>
                        </ul>
                      </footer>
                    </div>
                  </div>
                </div>
                <!-- Featured Listings / End -->
            
              </div>
            </div>
          </section>
          <!-- Light Section / End -->

          <!-- Section -->
          <section class="section section-nomargin">
            <div class="row">
              <div class="col-md-6" data-animation="fadeInLeft" data-animation-delay="0">
                <div class="img-box">
                  <img src="images/samples/img1.png" alt="">
                </div>
              </div>
              <div class="col-md-6">
                <h2>For Pet Owners</h2>
                <div class="icon-box circled icon-box-animated" data-animation="fadeInLeft" data-animation-delay="0">
                  <div class="icon">
                    <i class="entypo search"></i>
                  </div>
                  <div class="icon-box-body">
                    <h4>Find Your Perfect Pet Sitter</h4>
                    Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum.
                  </div>
                </div>

                <div class="icon-box circled icon-box-animated" data-animation="fadeInLeft" data-animation-delay="200">
                  <div class="icon">
                    <i class="entypo vcard"></i>
                  </div>
                  <div class="icon-box-body">
                    <h4>Contact Pet Sitter</h4>
                    Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum.
                  </div>
                </div>

                <div class="icon-box circled icon-box-animated" data-animation="fadeInLeft" data-animation-delay="400">
                  <div class="icon">
                    <i class="entypo check"></i>
                  </div>
                  <div class="icon-box-body">
                    <h4>Hire with Confidence</h4>
                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum.</p>
                  </div>
                </div>

                <a href="job-list.html" class="btn btn-primary">View All Pet Sitters <i class="fa fa-arrow-circle-o-right fa-lg fa-right"></i></a>

              </div>
            </div>

            <hr class="lg">


          </section>
          <!-- Section / End -->

        </div>
      </section>
      <!-- Page Content / End -->
    </div>
    <!-- Main / End -->
</div>

<script>
  jQuery(function($){
    $('body').addClass('loading');
  });
  
  $(window).load(function(){
    $('.flexslider').flexslider({
      animation: "fade",
      controlNav: true,
      directionNav: false,
      prevText: "",
      nextText: "",
      start: function(slider){
        $('body').removeClass('loading');
      }
    });
  });
</script>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: "Perfil de #{@user.name}" } %>

<section class="page-content">
  <div class="container">

    <div class="row">
      <div class="col-md-5">
        <figure class="alignnone">
          <% image = @user.image.nil? ? 'profile_default.png' : @user.image %>
          <%= image_tag(image, class: 'profile-picture-big') %>
        </figure>
      </div>

      <div class="col-md-7">
        <div class="spacer visible-sm visible-xs"></div>
        <div class="team-single-head">
          <h2><%= @user.name %></h2>
        </div>

        <h5>Perfil</h5>

        <dl class="dl-horizontal">
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
        </dl>

        <%= link_to 'Editar', edit_user_path(id: current_user.id), class: "btn btn-sm btn-warning" %>

        <br/><br/>

        <%= link_to 'Nuevo extravío', new_lost_report_path, class: "btn btn-sm btn-warning" %>
        <%= link_to 'Nueva adopción', new_adoption_path, class: "btn btn-sm btn-warning" %>
      </div>
    </div>

    <hr class="lg">

    <h3>Tus mascotas agregadas</h3>
    <%= render 'shared/pets_grid' %>

  </div>
</section>