config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lost_reports, path: 'extravios' do
    resource :flyer do
      get :show
      get :preview
    end
  end

  resources :adoptions, path: 'adopciones'
  resources :users, only: [:show, :edit, :update]
  resources :invites, only: :create

  get 'contacto', to: 'main#contact', as: 'contact'
  get 'perfil', to: 'users#show', as: 'profile'

  root 'adoptions#index'
end

app/views/shared/_adoption_info.html.erb
<% pet = adoption.pet %>

<div class="pet-name">
  <p>¡Adoptá a <%= pet.name %>! <%= link_to '(editar mascota)', edit_adoption_path(adoption) if current_user == adoption.user %></p>
</div>

<fieldset class="pet-field">
  <%= image_tag("breed_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= pet.breed_name %></b> (<%= pet.sex %>)
  </div>
</fieldset>

<% if pet.castrated %>
  <fieldset class="pet-field">
    <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
    <div class="lostPet__information__detail__text">
      Está castrado
    </div>
  </fieldset>
<% end %>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b>Edad: </b><%= pet.age %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("size_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b>Tamaño: </b><%= pet.size %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <%= adoption.description %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("phone_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= adoption.phone_numbers.join(' / ') %></b> (con <%= adoption.contact %>)
  </div>
</fieldset>

app/views/shared/_default_social_meta_tags.html.erb
<!-- Facebook -->
<meta property="fb:app_id" content="<%= ENV['FACEBOOK_APP_ID'] %>" />
<meta property="og:site_name" content="Misingo"/>
<meta property="og:type" content="website" />
<meta property="og:image:width" content="600" />
<meta property="og:image:height" content="315" />
<meta property="og:url" content="<%= request.base_url %>" />
<meta property="og:title" content="¡Somos Misingo.com!" />
<meta property="og:description" content="Te ayudamos a encontrar a tu mascota desaparecida y con adopciones de mascotas." />
<meta property="og:image" content="https://s3.amazonaws.com/mascotaproject/misingo_share_big_color.png" />

<!-- Twitter -->
<meta name="twitter:title" content="¡Somos Misingo.com!">
<meta name="twitter:description" content="Te ayudamos a encontrar a tu mascota desaparecida y con adopciones de mascotas.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@misingocom">
<meta name="twitter:creator" content="@misingocom">
<meta name="twitter:image" content="https://s3.amazonaws.com/mascotaproject/misingo_share_big_color.png">

app/views/shared/_defer_js.html.haml
%script
  defer_js_file = "#{asset_path('application-defer.js')}"

:coffee
  downloadJSAtOnload = ->
    element = document.createElement("script")
    element.src = defer_js_file
    document.body.appendChild element

  if window.addEventListener
    window.addEventListener "load", downloadJSAtOnload, false

  else if window.attachEvent
    window.attachEvent "onload", downloadJSAtOnload

  else
    preExistingOnload = window.onload
    window.onload = ->
      setTimeout downloadJSAtOnload, 0
      preExistingOnload?()

app/views/shared/_facebook_meta_tags.html.erb
<meta property="fb:app_id" content="<%= ENV['FACEBOOK_APP_ID'] %>" />
<meta property="og:site_name" content="Misingo"/>
<meta property="og:type" content="article" />
<meta property="article:publisher" content="https://www.facebook.com/misingocom" />
<meta property="article:author" content="https://www.facebook.com/misingocom" />
<meta property="og:image:width" content="600" />
<meta property="og:image:height" content="315" />

app/views/shared/_flash_messages.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"><i class="fa fa-times"></i></button>
    <strong>¡Oh!</strong> No se pudo guardar la información, revisá estos detalles:<br>
    <% flash[:error].each do |attr, messages| %>
      <% messages.each do | msg | %>
        <i class="fa fa-times"></i> <%= msg.capitalize %><br>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_flyer_preview.html.erb
<div class="alert alert-warning alert-dismissable flyer-container">
  <fieldset>
    <%= image_tag url_for(preview_lost_report_flyer_path(@lost_report)), class: 'flyer-preview' %>
  </fieldset>
  <fieldset>
    <%= link_to(lost_report_flyer_path(lost_report), class: 'btn btn-sm btn-warning', target: '_blank') do %>
        Generar flyer
    <% end %>
    <%= link_to(lost_report_flyer_path(lost_report), download: 'misingo-flyer.jpg', class: 'btn btn-sm btn-warning', target: '_blank') do %>
        Descargar
    <% end %>
  </fieldset>
</div>

app/views/shared/_header.html.erb
<header class="header header-menu-fullw">
  <% if current_user.nil? %>
    <div class="header-top">
      <div class="container">
        <div class="header-top-left">
          <ul class="header-top-nav">
            <li><%= link_to 'Contacto', contact_path %></li>
          </ul>
        </div>
        <div class="header-top-right">
          <span class="register">
            ¿Tenés cuenta?
            <%= link_to 'Iniciar', new_user_session_path, class: "btn btn-sm btn-warning" %>
            <%= button_to 'Ingresar con Facebook', user_omniauth_authorize_path(:facebook), class: "btn btn-sm btn-warning facebook" %>
          </span>
        </div>
      </div>
    </div>
  <% else %>
    <div class="header-top">
      <div class="container">
        <div class="header-top-left">
          <ul class="header-top-nav">
            <li><%= link_to 'Contacto', contact_path %></li>
          </ul>
        </div>
        <div class="header-top-right">
          <div class="user-info">
            <%= link_to 'Nuevo extravío', new_lost_report_path, class: "btn btn-sm btn-warning web-only" %>
            <%= link_to 'Nueva adopción', new_adoption_path, class: "btn btn-sm btn-warning web-only" %>
            <% image = current_user.image.nil? ? 'profile_default.png' : current_user.image %>
            <%= link_to truncate(current_user.name, length: 20), user_path(current_user), class: 'username' %>
            <%= link_to image_tag(image, class:'small-picture'), user_path(current_user) %>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="header-main">
    <% if !@header_main %>
      <div class="container">
        <!-- Logo -->
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag('https://s3.amazonaws.com/mascotaproject/misingo_logo_small.svg') %>
          <% end %>
        </div>
        <!-- Logo / End -->
        <button type="button" class="navbar-toggle">
          <i class="fa fa-bars"></i>
        </button>
        <!-- Banner -->
        <div class="head-info">
          <ul class="head-info-list">
            <li><span>Adopciones y mascotas desaparecidas </span>en Costa Rica</li>
          </ul>
          <ul class="social-links">
            <li>
              <%= link_to 'https://www.facebook.com/misingocom', target: '_blank' do %><i class="fa fa-facebook"></i><% end %>
            </li>
            <li>
              <%= link_to 'https://www.twitter.com/misingocom', target: '_blank' do %><i class="fa fa-twitter"></i><% end %>
            </li>
<!--             <li>
              <%= link_to 'https://www.instagram.com/misingocom', target: '_blank' do %><i class="fa fa-instagram"></i><% end %>
            </li> -->
          </ul>
        </div>
        <!-- Banner / End -->
      </div>
    <% end %>
  </div>

  <%= render 'shared/mobile_nav_bar' %>
</header>

app/views/shared/_lost_pet_info.html.erb
<% pet = lost_report.pet %>

<div class="pet-name">
  <p>Se busca <%= pet.name %> <%= link_to '(editar mascota)', edit_lost_report_path(lost_report) if current_user == lost_report.user %></p>
</div>

<fieldset class="pet-field">
  <%= image_tag("breed_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= pet.breed_name %></b> (<%= pet.sex %>)
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("location_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= lost_report.province.name %></b>. <%= lost_report.address %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <%= lost_report.description %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("phone_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= lost_report.phone_numbers.join(' / ') %></b> (con <%= lost_report.owner %>)
  </div>
</fieldset>

app/views/shared/_lost_report_info.html.erb
<% pet = lost_report.pet %>

<div class="pet-name">
  <p>Se busca <%= pet.name %> <%= link_to '(editar mascota)', edit_lost_report_path(lost_report) if current_user == lost_report.user %></p>
</div>

<fieldset class="pet-field">
  <%= image_tag("breed_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= pet.breed_name %></b> (<%= pet.sex %>)
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("location_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= lost_report.province.name %></b>. <%= lost_report.address %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <%= lost_report.description %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("phone_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= lost_report.phone_numbers.join(' / ') %></b> (con <%= lost_report.owner %>)
  </div>
</fieldset>

app/views/shared/_mobile_nav_bar.html.erb
<nav class="nav-main">
  <div class="container">
    <ul data-breakpoint="992" class="flexnav">
      <% if current_user.nil? %>
        <li class="mobile-only"><%= link_to 'Ingresar con Facebook', user_omniauth_authorize_path(:facebook) %></li>
        <li class="mobile-only"><%= link_to 'Iniciar', new_user_session_path %></li>
      <% else %>
        <li class="mobile-only"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
        <li class="mobile-only"><%= link_to 'Agregar mascota en adopción', new_adoption_path %></li>
        <li class="mobile-only"><%= link_to 'Agregar mascota extraviada', new_lost_report_path %></li>
      <% end %>
      <li><%= link_to 'Adopciones', adoptions_path %></li>
      <li><%= link_to 'Extravíos', lost_reports_path %></li>
      <li><%= link_to 'Contacto', contact_path %></li>
    </ul>
  </div>
</nav>

app/views/shared/_page_heading.html.erb
<section class="page-heading">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1><%= heading %></h1>
      </div>
      <div class="col-md-6">
        <ul class="breadcrumb">
          <li><%= link_to 'En adopción', adoptions_path %></li>
          <li><%= link_to 'Extraviadas', lost_reports_path %></li>
          <li><%= link_to 'Contacto', contact_path %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/shared/_pets_grid.html.haml
#pets-grid
  - if @pet_reports.count == 0
    .text-center.no-results
      %b= "No hay resultados para la provincia seleccionada"
  .page-content.main
    .container
      .project-feed.project-feed__3cols.row.isotope
        - @pet_reports.each do |pet_report, pet = pet_report.pet|
          - unavailable = (pet_report.class == Adoption) ? pet_report.adopted : pet_report.found
          .col-sm-6.col-md-4.project-item.lostPet.js--onHoverShowElement{ data: { element: ".js--lostPet__information", unavailable: "#{unavailable}" } }
            .project-item-inner
              - if unavailable
                - message = pet_report.class == Adoption ? 'Adoptado' : 'Encontrado'
                .unavailable{class: (pet_report.class == Adoption ? 'adopted' : 'found')} #{message.upcase}
              %figure.alignnone.project-img
                .lostPet__imageHolder{:class => ("opacy" unless !unavailable)}
                  = image_tag pet.avatar.url(:medium), class: "lostPet__image"

              .project-desc{class: ("opacy" unless !unavailable)}
                - headline = (pet_report.class == Adoption) ? 'En adopción' : 'Se busca'
                %h5.lostPet__search #{headline}
                %h4.title.lostPet__name= pet.name

            .lostPet__information.hidden.js--lostPet__information
              %h4.lostPet__name= pet.name
              - path = (pet_report.class == Adoption) ? adoption_path(pet_report) : lost_report_path(pet_report)
              = link_to "Ver más detalles", path, class: "lostPet__information__moreLink btn btn-success mobile-only"
              .lostPet__information--detail
                .lostPet__information__detail__row.col-md-12.col-sm-12
                  = image_tag("location_icon.svg", class: "lostPet__information__detail__image")
                  .lostPet__information__detail__text
                    %b= pet_report.province.name

                .lostPet__information__detail__row.col-md-12.col-sm-12
                  = image_tag("breed_icon.svg", class: "lostPet__information__detail__image")
                  .lostPet__information__detail__text
                    %b= pet.breed_name
                    %span= "(#{pet.sex})"

                .lostPet__information__detail__row.col-md-12.col-sm-12
                  = image_tag("description_icon.svg", class: "lostPet__information__detail__image")
                  .lostPet__information__detail__text
                    %p= truncate(pet_report.description, length: 28)

                .lostPet__information__detail__row.col-md-12.col-sm-12
                  = image_tag("phone_icon.svg", class: "lostPet__information__detail__image")
                  .lostPet__information__detail__text
                    %p= pet_report.phone_numbers.join(" / ")
                    - contact = (pet_report.class == Adoption) ? pet_report.contact : pet_report.owner
                    %b= contact
              - path = (pet_report.class == Adoption) ? adoption_path(pet_report) : lost_report_path(pet_report)
              = link_to "Ver más detalles", path, class: "lostPet__information__moreLink btn btn-success web-only"
      .text-center
        - if controller_name != 'users'
          = paginate @pet_reports

app/views/shared/_site_slogan.html.erb
<strong>Gracias por tu ayuda.</strong>
<div>Recordá que podés buscar más <%= link_to 'mascotas en adopción', adoptions_path %>
  y <%= link_to 'reportar extravíos', lost_reports_path %>
  en <strong><%= link_to 'misingo.com', root_path %></strong>
</div>

app/views/shared/_twitter_meta_tags.html.erb
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@misingocom">
<meta name="twitter:creator" content="@misingocom">