config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lost_reports, path: 'extravios' do
    resource :flyer do
      get :show
      get :preview
    end
  end

  resources :adoptions, path: 'adopciones'
  resources :users, only: [:show, :edit, :update]
  resources :invites, only: :create

  get 'contacto', to: 'main#contact', as: 'contact'
  get 'perfil', to: 'users#show', as: 'profile'

  root 'adoptions#index'
end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  paginates_per 12

  belongs_to :province
  belongs_to :pet
  belongs_to :user
  accepts_nested_attributes_for :pet, allow_destroy: true

  delegate :name, :avatar, :breed_name, to: :pet, prefix: true
  delegate :animal_type_name, to: :pet

  serialize :phone_numbers
  before_validation :strip_phone_numbers
  validates :phone_numbers, phone_number: true
  validates_presence_of :contact, :description

  default_scope { order('created_at DESC') }

  def phone_numbers
    (super || []).reject(&:blank?)
  end

  private

  def strip_phone_numbers
    self.phone_numbers = phone_numbers.map { |phone_number| phone_number.delete('^0-9') }
  end
end

# == Schema Information
#
# Table name: adoptions
#
#  id            :integer          not null, primary key
#  description   :text
#  contact       :string
#  phone_numbers :text
#  province_id   :integer
#  pet_id        :integer
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  adopted       :boolean          default(FALSE)
#

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  before_filter :find_adoption, only: [:show, :edit, :update]
  before_filter :validate_owner, only: [:edit, :update]
  before_filter :find_all_adoptions, only: [:index]
  before_filter :filter_adoptions, only: [:index]
  before_action :authenticate_user!, only: [:new, :edit]

  def index; end

  def new
    @adoption = Adoption.new
    @adoption.build_pet
  end

  def create
    @adoption = current_user.adoptions.new(adoption_params)
    if @adoption.save
      redirect_to adoption_path(@adoption)
    else
      flash.now[:error] = @adoption.errors.messages
      render 'new'
    end
  end

  def edit; end

  def show; end

  def update
    if @adoption.update(adoption_params)
      redirect_to adoption_path(@adoption)
    else
      flash.now[:error] = @adoption.errors.messages
      render 'edit'
    end
  end

  private

  def find_all_adoptions
    @pet_reports = Adoption.all.page params[:page]
  end

  def filter_adoptions
    if params[:province].nil? || params[:province][:province_id].empty?
      find_all_adoptions
    else
      @pet_reports = find_all_adoptions.where(province_id: params[:province][:province_id]).page params[:page]
      @province_id = params[:province][:province_id]
    end
  end

  def find_adoption
    @adoption = Adoption.find(params[:id])
  end

  def validate_owner
    redirect_to root_path unless current_user == @adoption.user
  end

  def adoption_params
    params.require(:adoption).permit(
      :province_id,
      :description,
      :contact,
      :adopted,
      phone_numbers: [],
      pet_attributes: [:id, :name, :breed_id, :sex, :avatar,
                       :castrated, :age, :size]
    )
  end
end

app/views/adoptions/_adopted_info.html.erb
<% pet = adoption.pet %>

<div class="pet-name">
  <p>¡<%= pet.name %> ya tiene nuevo hogar! <%= link_to '(editar mascota)', edit_adoption_path(adoption) if current_user == adoption.user %></p>
</div>

<fieldset class="pet-field">
  <%= image_tag("breed_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b><%= pet.breed_name %></b> (<%= pet.sex %>)
  </div>
</fieldset>

<% if pet.castrated %>
  <fieldset class="pet-field">
    <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
    <div class="lostPet__information__detail__text">
      Está castrado
    </div>
  </fieldset>
<% end %>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b>Edad: </b><%= pet.age %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("size_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <b>Tamaño: </b><%= pet.size %>
  </div>
</fieldset>

<fieldset class="pet-field">
  <%= image_tag("description_icon.svg", class: "lostPet__information__detail__image") %>
  <div class="lostPet__information__detail__text">
    <%= adoption.description %>
  </div>
</fieldset>

app/views/adoptions/_form.html.erb
<%= form_for(@adoption, html: { class: 'job-manager-form' }) do |f, pet = @adoption.pet| %>
  <%= render 'shared/flash_messages' %>

  <%= f.fields_for :pet do |pet_form| %>
    <% if !pet.new_record? %>
      <fieldset>
        <div class='large-6 columns'>
          <div class="checkbox checkbox__custom checkbox__style4">
            <label>
              <%= f.check_box :adopted %>
              <span>¿Ya se dio en adopción?</span>
            </label>
          </div>
        </div>
      </fieldset>
    <% end %>

    <fieldset>
      <label>Foto de perfil <span class="required">*</span></label>
      <div class="field">
        <div class='profile-pic-box'>
          <% profile_img = !pet.new_record? ? pet.avatar.url(:profile) : 'profile-default.png' %>
          <%= image_tag profile_img, id: 'image', class: 'img-rounded' %>
        </div>
      </div>

      <div class="field">
        <div class='fileUpload btn btn-primary btn-sm'>
          <span>Subir imagen</span>
          <%= pet_form.file_field :avatar, { id: 'image-selector', class: 'upload' } %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <label>Nombre de la mascota <span class="required">*</span></label>
      <div class="field">
        <% @focus = pet.new_record? %>
        <%= pet_form.text_field :name, placeholder: 'ej. Misingo', class: 'form-control', autofocus: @focus  %>
      </div>
    </fieldset>

    <fieldset>
      <div class="row">
        <div class="col-md-6">
          <div class="radio radio__custom radio__style4">
            <label>
              <%= pet_form.radio_button :sex, 'Macho', checked: true %>
              <span>Es macho</span>
            </label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="radio radio__custom radio__style4">
            <label>
              <%= pet_form.radio_button :sex, 'Hembra'%>
              <span>Es hembra</span>
            </label>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="row">
      <div class="col-md-6">
        <fieldset class="fieldset-job_type">
          <label>Animal</label>
          <div class="field select-style">
            <% animal_selected = pet.new_record? ? 0 : pet.breed.animal_type_id %>
            <%= select_tag :animal_type_id, options_from_collection_for_select(AnimalType.all, :id, :name, selected: animal_selected), class: 'form-control' %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset>
          <label>Raza</label>
          <div class="field select-style">
            <% breed_selected = pet.new_record? ? 1 : pet.breed.id %>
            <%= pet_form.select :breed_id, options_for_select(Breed.order(:name).map{ |c| [c.name, c.id, { data: { animal_type: c.animal_type_id } } ] }, selected: breed_selected), {}, {class: 'form-control', id: 'pet_breed_id'} %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <fieldset class="fieldset-job_type">
          <label>Tamaño</label>
          <%= pet_form.select :size, options_for_select(['Pequeño', 'Mediano', 'Grande'], 'Mediano'), {}, class: 'form-control' %>
        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset class="fieldset-job_type">
          <label>Edad</label>
          <%= pet_form.select :age, options_for_select(['Cachorro', 'Joven', 'Adulto', 'Viejo'], 'Cachorro'), {}, class: 'form-control' %>
        </fieldset>
      </div>
    </div>

    <fieldset>
      <div class='large-6 columns'>
        <div class="checkbox checkbox__custom checkbox__style4">
          <label>
            <%= pet_form.check_box :castrated %>
            <span>Está castrado</span>
          </label>
        </div>
      </div>
    </fieldset>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <fieldset class="fieldset-job_type">
        <label> ¿En qué provincia está el animal?</label>
        <div class="field select-style">
          <% province_selected = @adoption.new_record? ? 0 : @adoption.province_id %>
          <%= collection_select(:adoption, :province_id, Province.all, :id, :name, {selected: province_selected}, {class: 'form-control'}) %>
        </div>
      </fieldset>
    </div>
  </div>

  <fieldset>
    <label>Tu nombre o el nombre de la organización pro animal <span class="required">*</span></label>
    <div class="field">
      <%= f.text_field :contact, placeholder: 'ej. María Soto o Asociación Animal Feliz', class: 'form-control' %>
    </div>
  </fieldset>

  <div class='row'>
    <div class="col-md-6">
      <fieldset>
        <label>Número de teléfono <span class="required">*</span></label>
        <%= f.text_field :phone_numbers, value: @adoption.phone_numbers[0], name: 'adoption[phone_numbers][]', class: 'form-control', placeholder: 'ej. 88112233' %>
      </fieldset>
    </div>
    <div class="col-md-6">
      <fieldset>
        <label>Otro teléfono (opcional)</label>
        <%= f.text_field :phone_numbers, value: @adoption.phone_numbers[1] , name: 'adoption[phone_numbers][]', class: 'form-control', placeholder: 'ej. 88112244' %>
      </fieldset>
    </div>
  </div>

  <fieldset>
    <div class="field">
      <label>Mencioná características del animal <span class="required">*</span></label>
      <%= f.text_area :description, placeholder: '¿Comportamiento?, ¿Estado de salud?', class: 'form-control' %>
    </div>
  </fieldset>

  <p>
    <% text = @adoption.pet.new_record? ? 'Agregar a la mascota' : 'Guardar cambios' %>
    <%= f.submit text, class: 'btn btn-primary', data: { disable_with: 'Guardando' } %>
  </p>
<% end %>

<script type='text/javascript'>
  <% if !@adoption.pet.new_record? %>
    setTimeout(function(){
      $('#pet_breed_id').val('<%= @adoption.pet.breed.id %>');
    },100);
  <% end %>
</script>

app/views/adoptions/_social_share_buttons.html.erb
<% pet = adoption.pet %>
<div class="alert alert-warning alert-dismissable social-share">
  <strong>¡No olvidés compartirlo en redes sociales!</strong>
  <% url = adoption_url(adoption) %>
  <div id='fb-root'></div>
  <div class="social-networks-buttons">
    <div class='fb-like' data-href='<%= url %>' data-layout='button' data-action='like' data-show-faces='true' data-share='true'></div>
    <a href='https://twitter.com/share' class='twitter-share-button' data-url='<%= url %>' data-text="¡<%= @adoption.pet.name %> en adopción! RT #Misingo" data-via='misingocom' data-count='none'>Tweet</a>
  </div>
</div>

app/views/adoptions/_social_share_meta_tags.html.erb
<% content_for :facebook_meta_tags do %>
  <%= render 'shared/facebook_meta_tags' %>
  <meta property="og:url" content="<%= request.base_url + adoption_path(@adoption) %>" />
  <meta property="og:title" content="¡<%= @adoption.pet.name %> busca un hogar!" />
  <meta property="og:description" content="<%= @adoption.description %>. Llamar al <%= @adoption.phone_numbers.join(' / ') %>" />
  <meta property="og:image" content="<%= @adoption.pet.avatar.url(:preview) %>" />
<% end %>
<% content_for :twitter_meta_tags do %>
  <%= render 'shared/twitter_meta_tags' %>
  <meta name="twitter:title" content="¡<%= @adoption.pet.name %> busca un hogar! | Misingo">
  <meta name="twitter:description" content="<%= @adoption.description %>. Llamar al <%= @adoption.phone_numbers.join(' / ') %>">
  <meta name="twitter:image" content="<%= @adoption.pet.avatar.url(:preview) %>">
<% end %>

app/views/adoptions/_social_share_options.html.erb
<% pet = adoption.pet %>
<div class="alert alert-warning alert-dismissable social-share">
  <strong>¡No olvidés compartirlo en redes sociales!</strong>
  <% url = adoption_url(adoption) %>
  
  <div id='fb-root'></div>
  <div class="social-networks-buttons">
    <div class='fb-like' data-href='<%= url %>' data-layout='button' data-action='like' data-show-faces='true' data-share='true'></div>
    <a href='https://twitter.com/share' class='twitter-share-button' data-url='<%= url %>' data-text="¡<%= @adoption.pet.name %> busca hogar! Ayudame a darlo en adopción" data-via='misingocom' data-count='none'>Tweet</a>
  </div>
</div>

app/views/adoptions/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: "Editar datos de #{@adoption.pet.name}" } %>

<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/adoptions/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: 'Mascotas en adopción' } %>

<div class="row search">
  <div class="col-md-6 col-md-offset-4">
    <fieldset>
      <%= form_tag(adoptions_path, method: 'get') do %>
        <div class="col-md-6">
          <%= collection_select(:province, :province_id, Province.all, :id, :name,
          { include_blank: 'Provincias', selected: @province_id }, { class: 'form-control' }) %>
        </div>
        <div class="col-md-6">
          <%= button_tag('Buscar', class: 'btn btn-sm btn-default search') %>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>

<%= render 'shared/pets_grid' %>

app/views/adoptions/new.html.erb
<%= render 'shared/header' %>
<%= render 'shared/page_heading', { heading: 'Agregar mascota en adopción' } %>

<section class="page-content">
  <div class="container">  
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/adoptions/show.html.erb
<%= render 'social_share_meta_tags' %>
<%= render 'shared/header' %>
<% text = @adoption.adopted ? 'ya tiene nuevo hogar' : 'busca hogar' %>
<%= render 'shared/page_heading', { heading: "#{@adoption.pet.name} #{text}" } %>

<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="pet-image col-md-7">
        <%= image_tag(@adoption.pet.avatar.url(:large), class: 'img-thumbnail') %>
        <%= render 'social_share_buttons', { adoption: @adoption } %>
      </div>
      <div class="col-md-5">
        <% if @adoption.adopted %>
          <%= render 'adopted_info', { adoption: @adoption } %>
          <div class="alert alert-warning alert-dismissable flyer-container">
            <strong><%= "¡Ya #{@adoption.pet.name} se dio en adopción!" %></strong>
            <%= render 'shared/site_slogan' %>
          </div>
        <% else %>
          <%= render 'shared/adoption_info', { adoption: @adoption } %>
        <% end %>
      </div>
    </div>
  </div>
</section>